#!/usr/bin/osascript -l JavaScript

// Helpers
function envVar(varName) {
  return $.NSProcessInfo
    .processInfo
    .environment
    .objectForKey(varName).js
}

// Main
const ignoredFolders = envVar("ignored_folders").split("\n")
const unfilteredFolders = Application("Notes").folders()
const allFolders = unfilteredFolders.filter(unfiltered => !ignoredFolders.some(ignored => ignored === unfiltered.name()))
const allNotes = allFolders.flatMap(folder => folder.notes())

const sfItems = allNotes.flatMap(noteReference => {
  const note = noteReference.properties()
  const folder = note.container.name()

  if (ignoredFolders.find(folderName => folderName === folder)) return []

  return {
    uid: note.id,
    title: note.passwordProtected ? "🔒" + note.name : note.name,
    subtitle: folder,
    arg: note.id,
    match: folder + " " + note.name + " " + note.plaintext
  }
})

// Output JSON
sfItems.length > 0 ?
  JSON.stringify({ cache: { seconds: 300, loosereload: true }, items: sfItems }) :
  JSON.stringify({ items: [{ title: "No Notes Found", subtitle: "Ensure you have not ignored all folders in the configuration", valid: false }] })
